# Generated by Django 2.1.5 on 2022-02-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Sr.', 'Sr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Jr.', 'Jr')], max_length=30),
        ),
    ]
