# Generated by Django 2.1.5 on 2022-02-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20220221_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(choices=[('Ms.', 'Ms.'), ('Sr.', 'Sr.'), ('Jr.', 'Jr'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.')], max_length=30),
        ),
    ]
