# Generated by Django 2.1.5 on 2022-02-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20220221_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='prefix',
            field=models.CharField(choices=[('Sr.', 'Sr.'), ('Jr.', 'Jr.'), ('Mrs.', 'Mrs.'), ('Mr.', 'Mr.'), ('Ms.', 'Ms.')], default='', max_length=6),
        ),
    ]
