# Generated by Django 2.1.5 on 2022-02-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20220221_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='prefix',
        ),
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('Jr.', 'Jr.'), ('Sr.', 'Sr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Mr.', 'Mr.')], default='', max_length=6),
        ),
    ]
