# Generated by Django 2.1.5 on 2022-02-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20220221_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='type',
        ),
        migrations.AddField(
            model_name='profile',
            name='prefix',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Sr.', 'Sr.'), ('Ms.', 'Ms.'), ('Jr.', 'Jr.'), ('Mrs.', 'Mrs.')], default='', max_length=6),
        ),
    ]
