# Generated by Django 2.1.5 on 2022-02-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20220221_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefix',
            field=models.CharField(choices=[('Sr.', 'Sr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Mr.', 'Mr.'), ('Jr.', 'Jr.')], default='', max_length=6),
        ),
    ]
