# Generated by Django 2.1.5 on 2022-02-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20220221_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='prefix',
        ),
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Sr.', 'Sr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Jr.', 'Jr.')], default='', max_length=60),
        ),
    ]
